platform :ios, "7.0"

pod "Masonry"
pod "AFNetworking","~> 3.0.4"
pod "MBProgressHUD"
pod "SDWebImage"
pod "TPKeyboardAvoiding"
pod "SWTableViewCell"
pod "MJRefresh"
pod "MJExtension"
pod "RDVTabBarController"
pod 'SDCycleScrollView','~> 1.6'

target :TureTopValuePurchaseDemoTests, :exclusive => true do
  # pod 'Masonry'
end